import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import logo from '../public/images/dwf-logo.svg'

import Draggable from 'react-draggable';

const Tetris = require('react-tetris');

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Tetris
      keyboardControls={{
        // Default values shown here. These will be used if no
        // `keyboardControls` prop is provided.
        down: 'MOVE_DOWN',
        left: 'MOVE_LEFT',
        right: 'MOVE_RIGHT',
        space: 'HARD_DROP',
        z: 'FLIP_COUNTERCLOCKWISE',
        x: 'FLIP_CLOCKWISE',
        up: 'FLIP_CLOCKWISE',
        p: 'TOGGLE_PAUSE',
        c: 'HOLD',
        shift: 'HOLD'
      }}
    >
      {({
        HeldPiece,
        Gameboard,
        PieceQueue,
        points,
        linesCleared,
        state,
        controller
      }) => (
        <div>
          <HeldPiece />
          <div>
            <p>Points: {points}</p>
            <p>Lines Cleared: {linesCleared}</p>
          </div>
          <Gameboard />
          <PieceQueue />
          {state === 'LOST' && (
            <div>
              <h2>Game Over</h2>
              <button onClick={controller.restart}>New game</button>
            </div>
          )}
        </div>
      )}
    </Tetris>

      <main className={styles.main}>
        <h1 className="hide">
          Dinner with Friends
        </h1>

        <Image
        src={logo}
        className="logo"
        alt="Dinner with Friends"
      />

        <Draggable
        handle=".handle"
        defaultPosition={{x: 0, y: 50}}
        position={null}
        grid={[25, 25]}
        scale={1}>
          <div className={styles.card}>
            <div className="handle">▓▓▓▓▓▓▓▓▓▓▓▓▓▓</div>
            <div>Insert good stuff here please</div>
          </div>
        </Draggable>

        <Draggable
        handle=".handle"
        defaultPosition={{x: -100, y: 400}}
        position={null}
        grid={[25, 25]}
        scale={1}>
          <div className={styles.card}>
            <div className="handle">▓▓▓▓▓▓▓▓▓▓▓▓▓▓</div>
            <div>Insert good stuff here please</div>
          </div>
        </Draggable>

        <Draggable
        handle=".handle"
        defaultPosition={{x: 100, y: -500}}
        position={null}
        grid={[25, 25]}
        scale={1}>
          <div className={styles.card}>
            <div className="handle">▓▓▓▓▓▓▓▓▓▓▓▓▓▓</div>
            <div>Insert good stuff here please</div>
          </div>
        </Draggable>

        <Draggable
        handle=".handle"
        defaultPosition={{x: -300, y: 0}}
        position={null}
        grid={[25, 25]}
        scale={1}>
          <div className={styles.card}>
            <div className="handle">▓▓▓▓▓▓▓▓▓▓▓▓▓▓</div>
            <div>Insert good stuff here please</div>
          </div>
        </Draggable>

      </main>
    </div >
  )
}
