"use client"

import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import logo from '../public/images/dwf-logo.svg'

import Draggable from 'react-draggable';

import dynamic from 'next/dynamic'
//import Tetris from '../components/tetris';


const Tetris = dynamic(() => import("../components/tetris"), {
  ssr: false,
  });

export default function Home() {
  let date = new Date();
  setInterval(() => {
    date = new Date();
  }, 1000);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className={styles.main}>
        <nav className={styles.nav}>
        <div>Dinner with Friends</div>
        <div>Work</div>
        <div>About</div>
        <div>Knowledge</div>
        <div>Contact</div>
        <div className="grow"></div>
        <div>{date.toLocaleString('en-US', { weekday: 'long', month: 'long', day: 'numeric' })}</div>
        <div>{date.toLocaleString('en-US', { hour:   '2-digit', minute: '2-digit' })}</div>
        <div>Light • Dark</div>
        </nav>

        <h1 className="hide">
          Dinner with Friends
        </h1>

        <Image
        src={logo}
        className="logo"
        alt="Dinner with Friends"
      />

        <Draggable
        handle=".handle"
        defaultPosition={{x: 0, y: 50}}
        position={null}
        grid={[25, 25]}
        scale={1}>
          <div className={styles.card}>
            <div className="handle">▓▓▓▓▓▓▓▓▓▓▓▓▓▓</div>
            <div>TETRIS</div>
            <Tetris></Tetris>
          </div>
        </Draggable>

        <Draggable
        handle=".handle"
        defaultPosition={{x: -100, y: 0}}
        position={null}
        grid={[25, 25]}
        scale={1}>
          <div className={styles.card}>
            <div className="handle">▓▓▓▓▓▓▓▓▓▓▓▓▓▓</div>
            <div>Justin Graham</div>
            <img src="/images/justin.jpg" />
          </div>
        </Draggable>

        <Draggable
        handle=".handle"
        defaultPosition={{x: 100, y: -500}}
        position={null}
        grid={[25, 25]}
        scale={1}>
          <div className={styles.card}>
            <div className="handle">▓▓▓▓▓▓▓▓▓▓▓▓▓▓</div>
            <div>Alex Baldwin</div>
            <img src="/images/alex.jpg" />
          </div>
        </Draggable>

        <Draggable
        handle=".handle"
        defaultPosition={{x: -300, y: 0}}
        position={null}
        grid={[25, 25]}
        scale={1}>
          <div className={styles.card}>
            <div className="handle">▓▓▓▓▓▓▓▓▓▓▓▓▓▓</div>
            <div>Insert good stuff here please</div>
          </div>
        </Draggable>

      </main>
    </div >
  )
}
